//! The RS256 access tokens rustak issues, and the keys that sign them.
//!
//! One token format serves everything: the admin UI after a sign-in, CloudTAK
//! after `/oauth/token`, and sidecars. That is deliberate — a second format
//! would be a second thing to get subtly wrong — but it means the format is
//! pinned by the least forgiving consumer, and that consumer is CloudTAK.
//!
//! # The shape is a compatibility contract, not a preference
//!
//! node-tak, the library CloudTAK logs in with, does not verify our signature
//! or fetch our keys. It base64-decodes the **whole token string** as one blob
//! (the dots are simply not in the base64 alphabet, so they vanish), splits the
//! result on `}`, and parses the second piece as the claims. Three consequences
//! follow, and all three are asserted by the tests at the bottom of this file:
//!
//! 1. **The header bytes are fixed** at [`JWT_HEADER_JSON`]. It is 27 bytes — a
//!    whole number of three-byte groups — so its base64 is exactly 36
//!    characters and the payload that follows starts on a group boundary. A
//!    header of 26 or 28 bytes shifts every following byte and login fails with
//!    a decode error nobody would think to blame on the header.
//! 2. **Claims are flat scalars.** The payload must contain exactly one `}` —
//!    its own closing brace — so a nested object anywhere would truncate the
//!    claims at the inner brace. [`JwtIssuer::issue`] refuses to mint a token
//!    that breaks this rather than emitting one that fails mysteriously later.
//! 3. **`aud` is a string**, not the array the specification also permits.
//!
//! None of this weakens *our* verification: [`JwtIssuer::verify`] checks the
//! signature, requires RS256, and requires the audience, issuer and expiry.
//!
//! # Keys and rotation
//!
//! The signing key is RSA-2048, generated by the pure-Rust `rsa` crate, sealed
//! with [`SecretContext::JwtSigningKey`] and stored in `oauth_keys`. Retiring a
//! key does not delete it: tokens it signed stay verifiable until they expire,
//! which is what makes a rotation invisible to whoever is already signed in.
//! Tokens carry no `kid` — there is no room in a fixed 27-byte header — so
//! verification tries the active key and then each retired one.

use std::sync::LazyLock;

use base64::Engine as _;
use chrono::{Duration, Utc};
use jsonwebtoken::{Algorithm, DecodingKey, EncodingKey, Validation};
use rsa::pkcs1::EncodeRsaPrivateKey as _;
use rsa::pkcs8::{DecodePrivateKey as _, EncodePrivateKey as _, EncodePublicKey as _};
use rsa::traits::PublicKeyParts as _;
use rustak_core::prelude::*;
use sha2::{Digest as _, Sha256};

use crate::crypto::{SecretContext, SecretStore};
use crate::db::{
    Database,
    repos::{KeyAlgorithm, KeyPurpose, NewOauthKey},
};

/// The exact header every token we issue carries. See the module docs.
pub const JWT_HEADER_JSON: &str = r#"{"alg":"RS256","typ":"JWT"}"#;

/// The size of the keys we sign with. Every TAK client accepts RSA-2048, and
/// larger keys make the tokens larger without making them safer in any way that
/// matters over their one-hour life.
const KEY_BITS: usize = 2048;

/// How many bytes of the public key's digest name it.
const KID_BYTES: usize = 8;

/// The clock skew tolerated when checking `exp` and `nbf`.
const LEEWAY_SECONDS: u64 = 60;

/// Base64 as JSON Web Tokens use it: URL-safe alphabet, no padding.
const B64: base64::engine::general_purpose::GeneralPurpose =
    base64::engine::general_purpose::URL_SAFE_NO_PAD;

/// The header, encoded once.
static HEADER_B64: LazyLock<String> = LazyLock::new(|| B64.encode(JWT_HEADER_JSON));

/// Advice for a token failure that is ours rather than the caller's.
const ADVICE_REPORT: &[&str] =
    &["This is unexpected; please report it with the surrounding log entries."];

/// The claims of an access token.
///
/// Field order is wire order, and every value is a scalar. See the module
/// documentation for why that is not negotiable.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AccessClaims {
    /// The username the token speaks for.
    pub sub: String,
    /// Who the token is for. A string, never an array.
    pub aud: String,
    /// Who issued it: this server's base URL.
    pub iss: String,
    /// Issued at, seconds since the epoch.
    pub iat: i64,
    /// Not valid before.
    pub nbf: i64,
    /// Expires at.
    pub exp: i64,
    /// A unique identifier, so a token can be revoked before it expires.
    pub jti: String,
    /// Space-separated scopes.
    pub scope: String,
    /// The device this token was issued to, when it was issued to one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dev: Option<String>,
}

/// One RSA key pair, in every form the token path needs it.
struct SigningKey {
    kid: String,
    encoding: EncodingKey,
    decoding: DecodingKey,
    /// The public half, SPKI PEM, as `/oauth/token_key` publishes it.
    public_pem: String,
    /// The `n` and `e` a JSON Web Key carries, base64url.
    modulus: String,
    exponent: String,
}

impl SigningKey {
    /// Rebuilds a key from the PKCS#8 encoding we sealed.
    fn from_pkcs8(der: &[u8]) -> Result<Self, Error> {
        let private = rsa::RsaPrivateKey::from_pkcs8_der(der).or_system_err(&[
            "A stored token signing key could not be read; it may have been written by a different version of rustak.",
        ])?;
        let public = rsa::RsaPublicKey::from(&private);

        let spki = public.to_public_key_der().or_system_err(ADVICE_REPORT)?;
        let pkcs1 = private.to_pkcs1_der().or_system_err(ADVICE_REPORT)?;

        Ok(Self {
            kid: hex::encode(&Sha256::digest(spki.as_bytes())[..KID_BYTES]),
            encoding: EncodingKey::from_rsa_der(pkcs1.as_bytes()),
            decoding: DecodingKey::from_rsa_raw_components(
                &public.n().to_bytes_be(),
                &public.e().to_bytes_be(),
            ),
            public_pem: public
                .to_public_key_pem(rsa::pkcs8::LineEnding::LF)
                .or_system_err(ADVICE_REPORT)?,
            modulus: B64.encode(public.n().to_bytes_be()),
            exponent: B64.encode(public.e().to_bytes_be()),
        })
    }

    /// Generates a key and returns it beside its PKCS#8 encoding, for sealing.
    fn generate() -> Result<(Self, Vec<u8>), Error> {
        let private = rsa::RsaPrivateKey::new(&mut rsa::rand_core::OsRng, KEY_BITS)
            .or_system_err(ADVICE_REPORT)?;
        let pkcs8 = private.to_pkcs8_der().or_system_err(ADVICE_REPORT)?;

        Ok((
            Self::from_pkcs8(pkcs8.as_bytes())?,
            pkcs8.as_bytes().to_vec(),
        ))
    }

    /// The public half as a JSON Web Key.
    fn jwk(&self) -> serde_json::Value {
        serde_json::json!({
            "kty": "RSA",
            "use": "sig",
            "alg": "RS256",
            "kid": self.kid,
            "n": self.modulus,
            "e": self.exponent,
        })
    }
}

impl std::fmt::Debug for SigningKey {
    /// Written out so that a `{:?}` on anything holding a key cannot print the
    /// private half, which `EncodingKey` would otherwise be asked for.
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "SigningKey({})", self.kid)
    }
}

/// Issues and verifies this server's access tokens.
#[derive(Debug)]
pub struct JwtIssuer {
    active: SigningKey,
    /// Retired keys, kept so the tokens they signed stay verifiable.
    previous: Vec<SigningKey>,
    issuer: String,
    audience: String,
    ttl: Duration,
    validation: Validation,
}

impl JwtIssuer {
    /// Loads the signing keys, creating one on first run.
    ///
    /// `base_url` is this server's own URL, used as the issuer when `[auth]`
    /// does not name one.
    ///
    /// # Errors
    ///
    /// A [`human_errors::Kind::System`] error when a key cannot be generated,
    /// stored, read back or decrypted.
    #[instrument("auth.jwt.load", skip_all, err(Display))]
    pub async fn load_or_create(
        db: &Database,
        secrets: &SecretStore,
        auth: &crate::config::AuthConfig,
        base_url: &str,
    ) -> Result<Self, Error> {
        let stored = db.oauth_keys().list(KeyPurpose::AccessToken).await?;

        let (active, previous) = match stored.iter().find(|row| row.retired_at.is_none()) {
            Some(row) => (
                open_key(secrets, &row.kid, &row.private_sealed)?,
                stored
                    .iter()
                    .filter(|other| other.kid != row.kid)
                    .map(|other| open_key(secrets, &other.kid, &other.private_sealed))
                    .collect::<Result<Vec<_>, _>>()?,
            ),
            None => (
                create_key(db, secrets).await?,
                stored
                    .iter()
                    .map(|other| open_key(secrets, &other.kid, &other.private_sealed))
                    .collect::<Result<Vec<_>, _>>()?,
            ),
        };

        let issuer = auth.issuer.clone().unwrap_or_else(|| base_url.to_owned());
        let mut validation = Validation::new(Algorithm::RS256);

        // RS256 and nothing else: accepting `none` or an HMAC algorithm here is
        // the classic JWT forgery, because our verifying key is public.
        validation.algorithms = vec![Algorithm::RS256];
        validation.leeway = LEEWAY_SECONDS;
        validation.validate_exp = true;
        validation.validate_nbf = true;
        validation.set_audience(&[auth.audience.as_str()]);
        validation.set_issuer(&[issuer.as_str()]);
        validation.set_required_spec_claims(&["exp", "nbf", "aud", "iss", "sub"]);

        debug!(kid = %active.kid, retired = previous.len(), "Loaded the token signing keys.");

        Ok(Self {
            active,
            previous,
            issuer,
            audience: auth.audience.clone(),
            ttl: auth.access_token_ttl,
            validation,
        })
    }

    /// The identifier of the key tokens are currently signed with.
    pub fn active_kid(&self) -> &str {
        &self.active.kid
    }

    /// The `iss` claim this server puts in its tokens.
    pub fn issuer(&self) -> &str {
        &self.issuer
    }

    /// The `aud` claim this server issues and requires.
    pub fn audience(&self) -> &str {
        &self.audience
    }

    /// Mints an access token.
    ///
    /// # Errors
    ///
    /// A [`human_errors::Kind::System`] error when the claims could not be
    /// rendered in the flat form CloudTAK can parse, or when signing fails.
    pub fn issue(
        &self,
        subject: &Username,
        scope: &str,
        device: Option<&DeviceUid>,
        ttl: Option<Duration>,
    ) -> Result<(String, AccessClaims), Error> {
        let now = Utc::now();
        let claims = AccessClaims {
            sub: subject.as_str().to_owned(),
            aud: self.audience.clone(),
            iss: self.issuer.clone(),
            iat: now.timestamp(),
            nbf: now.timestamp(),
            exp: (now + ttl.unwrap_or(self.ttl)).timestamp(),
            jti: uuid::Uuid::new_v4().to_string(),
            scope: scope.to_owned(),
            dev: device.map(|uid| uid.as_str().to_owned()),
        };

        let payload = serde_json::to_vec(&claims).or_system_err(ADVICE_REPORT)?;

        // CloudTAK splits the decoded token on `}` and reads the second piece,
        // so a payload with a second brace — from a nested object, or from one
        // inside a claim's value — silently truncates its view of the claims.
        if payload.iter().filter(|byte| **byte == b'}').count() != 1 {
            return Err(human_errors::system(
                "We could not issue a token whose claims stay in the flat form TAK clients parse.",
                &[
                    "A scope or device identifier containing '}' cannot appear in a token; remove it and try again.",
                ],
            ));
        }

        let signing_input = format!("{}.{}", *HEADER_B64, B64.encode(&payload));
        let signature = jsonwebtoken::crypto::sign(
            signing_input.as_bytes(),
            &self.active.encoding,
            Algorithm::RS256,
        )
        .or_system_err(ADVICE_REPORT)?;

        Ok((format!("{signing_input}.{signature}"), claims))
    }

    /// Verifies a token this server issued and returns its claims.
    ///
    /// # Errors
    ///
    /// A [`human_errors::Kind::User`] error whenever the token is not one we
    /// would accept — a bad signature, the wrong algorithm, the wrong audience
    /// or issuer, or an expired or not-yet-valid window. The caller turns that
    /// into a 401 without distinguishing the cases, which is what keeps a token
    /// oracle out of the response.
    pub fn verify(&self, token: &str) -> Result<AccessClaims, Error> {
        let header = jsonwebtoken::decode_header(token).map_err(|_| rejected())?;

        if header.alg != Algorithm::RS256 {
            warn!(algorithm = ?header.alg, "Rejected a token that was not signed with RS256.");
            return Err(rejected());
        }

        let mut last = None;

        for key in std::iter::once(&self.active).chain(&self.previous) {
            match jsonwebtoken::decode::<AccessClaims>(token, &key.decoding, &self.validation) {
                Ok(data) => return Ok(data.claims),
                Err(err) => {
                    // Only a signature mismatch means "wrong key, try the next
                    // one". An expired or misaddressed token fails against
                    // every key, and retrying it would hide that.
                    if !matches!(
                        err.kind(),
                        jsonwebtoken::errors::ErrorKind::InvalidSignature
                    ) {
                        return Err(rejected());
                    }

                    last = Some(err);
                }
            }
        }

        debug!(error = ?last.map(|err| err.to_string()), "Rejected a token no signing key matched.");

        Err(rejected())
    }

    /// The `/oauth/token_key` body, in the Spring Security shape TAK clients
    /// expect: an algorithm name and the public key as PEM.
    pub fn token_key_json(&self) -> serde_json::Value {
        serde_json::json!({ "alg": "SHA256withRSA", "value": self.active.public_pem })
    }

    /// The JSON Web Key Set: the active key first, then every retired key whose
    /// tokens could still be presented.
    pub fn jwks(&self) -> serde_json::Value {
        let keys: Vec<_> = std::iter::once(&self.active)
            .chain(&self.previous)
            .map(SigningKey::jwk)
            .collect();

        serde_json::json!({ "keys": keys })
    }

    /// Starts signing with a fresh key, keeping the old one for verification.
    ///
    /// # Errors
    ///
    /// A [`human_errors::Kind::System`] error when the new key cannot be
    /// generated or stored.
    #[instrument("auth.jwt.rotate", skip_all, err(Display))]
    pub async fn rotate(&mut self, db: &Database, secrets: &SecretStore) -> Result<(), Error> {
        let replacement = create_key(db, secrets).await?;
        let retiring = std::mem::replace(&mut self.active, replacement);

        db.oauth_keys().retire(&retiring.kid).await?;

        info!(
            retired = %retiring.kid,
            active = %self.active.kid,
            "Rotated the token signing key."
        );

        self.previous.push(retiring);

        Ok(())
    }
}

/// The single rejection every verification failure collapses to.
fn rejected() -> Error {
    human_errors::user(
        "Your session is no longer valid.",
        &["Sign in again to continue."],
    )
}

/// Unseals a stored key.
fn open_key(secrets: &SecretStore, kid: &str, sealed: &str) -> Result<SigningKey, Error> {
    let sealed = serde_json::from_str(sealed).or_system_err(&[
        "A stored token signing key is corrupt; removing it will make rustak mint a new one.",
    ])?;

    SigningKey::from_pkcs8(&secrets.open(&sealed, SecretContext::JwtSigningKey { kid })?)
}

/// Generates a key, seals it and records it as the one to sign with.
async fn create_key(db: &Database, secrets: &SecretStore) -> Result<SigningKey, Error> {
    // RSA generation is bignum arithmetic measured in hundreds of
    // milliseconds, which would otherwise stall this worker thread.
    let (key, pkcs8) = tokio::task::spawn_blocking(SigningKey::generate)
        .await
        .or_system_err(ADVICE_REPORT)??;

    let sealed = secrets.seal(&pkcs8, SecretContext::JwtSigningKey { kid: &key.kid })?;

    db.oauth_keys()
        .create(NewOauthKey {
            kid: key.kid.clone(),
            alg: KeyAlgorithm::Rs256,
            purpose: KeyPurpose::AccessToken,
            public_jwk: Some(key.jwk().to_string()),
            private_sealed: serde_json::to_string(&sealed).or_system_err(ADVICE_REPORT)?,
        })
        .await?;

    info!(kid = %key.kid, "Created a token signing key.");

    Ok(key)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn auth() -> crate::config::AuthConfig {
        crate::config::AuthConfig {
            issuer: Some("https://tak.example.com".to_string()),
            ..crate::config::AuthConfig::default()
        }
    }

    async fn issuer() -> (Database, SecretStore, JwtIssuer) {
        let db = Database::open_in_memory().await.unwrap();
        let secrets = SecretStore::ephemeral();
        let jwt = JwtIssuer::load_or_create(&db, &secrets, &auth(), "https://unused")
            .await
            .unwrap();

        (db, secrets, jwt)
    }

    fn user() -> Username {
        Username::parse("j.smith").unwrap()
    }

    /// node-tak's claim parser, transcribed from its behaviour.
    ///
    /// `Buffer.from(jwt, 'base64')` decodes the **whole token** as one blob:
    /// `.` is not in the alphabet so it simply vanishes, and Node accepts the
    /// URL-safe characters and a trailing partial group. The result is then
    /// split on `}` and the second piece parsed as the claims — so this only
    /// yields the right object when our header is a whole number of base64
    /// groups and our payload holds exactly one brace.
    fn cloudtak_parse(token: &str) -> serde_json::Value {
        let joined: String = token
            .chars()
            .filter(|character| *character != '.')
            .map(|character| match character {
                '-' => '+',
                '_' => '/',
                other => other,
            })
            .collect();

        // Node decodes a trailing partial group; the claims are at the front,
        // so dropping it here reaches the same bytes.
        let whole = &joined[..joined.len() - joined.len() % 4];
        let decoded = base64::engine::general_purpose::STANDARD_NO_PAD
            .decode(whole.as_bytes())
            .expect("node-tak decodes whatever it is given");
        let text = String::from_utf8_lossy(&decoded);

        let pieces: Vec<_> = text.split('}').map(|piece| format!("{piece}}}")).collect();
        assert!(pieces.len() >= 2, "Unexpected TAK JWT Format");

        serde_json::from_str(&pieces[1]).expect("the second piece must be the claims object")
    }

    #[tokio::test]
    async fn the_header_is_the_documented_bytes_exactly() {
        let (_db, _secrets, jwt) = issuer().await;
        let (token, _) = jwt.issue(&user(), "admin", None, None).unwrap();

        let header = token.split('.').next().unwrap();
        let decoded = B64.decode(header).unwrap();

        assert_eq!(decoded, JWT_HEADER_JSON.as_bytes());
        assert_eq!(
            JWT_HEADER_JSON.len(),
            27,
            "27 bytes is nine whole base64 groups"
        );
        assert_eq!(
            header.len(),
            36,
            "a shifted payload breaks CloudTAK's parser"
        );
        assert!(!header.contains('='), "padding would shift the payload too");
    }

    #[tokio::test]
    async fn cloudtaks_lenient_parser_reads_the_subject() {
        let (_db, _secrets, jwt) = issuer().await;
        let (token, claims) = jwt.issue(&user(), "marti admin", None, None).unwrap();

        let parsed = cloudtak_parse(&token);

        assert_eq!(parsed["sub"], "j.smith");
        assert_eq!(parsed["sub"], claims.sub);
        assert_eq!(parsed["aud"], "rustak");
        assert!(parsed["exp"].is_number());
        assert!(parsed["iat"].is_number());
        assert!(parsed["nbf"].is_number());
    }

    #[tokio::test]
    async fn the_payload_carries_exactly_one_closing_brace() {
        let (_db, _secrets, jwt) = issuer().await;
        let uid = DeviceUid::parse("ANDROID-1").unwrap();
        let (token, _) = jwt.issue(&user(), "marti", Some(&uid), None).unwrap();

        let payload = B64.decode(token.split('.').nth(1).unwrap()).unwrap();

        assert_eq!(payload.iter().filter(|b| **b == b'}').count(), 1);
        assert_eq!(cloudtak_parse(&token)["dev"], "ANDROID-1");
    }

    #[tokio::test]
    async fn a_claim_that_would_break_the_lenient_parser_is_refused() {
        let (_db, _secrets, jwt) = issuer().await;

        // Better a failed sign-in with a clear error than a token that parses
        // to the wrong claims on the other side.
        assert!(jwt.issue(&user(), "marti}admin", None, None).is_err());
    }

    #[tokio::test]
    async fn a_token_we_issued_verifies() {
        let (_db, _secrets, jwt) = issuer().await;
        let (token, claims) = jwt.issue(&user(), "admin", None, None).unwrap();

        assert_eq!(jwt.verify(&token).unwrap(), claims);
        assert_eq!(claims.iss, "https://tak.example.com");
        assert_eq!(claims.exp - claims.iat, 3_600);
        assert!(!claims.jti.is_empty());
    }

    #[tokio::test]
    async fn two_tokens_never_share_an_identifier() {
        let (_db, _secrets, jwt) = issuer().await;

        let (_, first) = jwt.issue(&user(), "admin", None, None).unwrap();
        let (_, second) = jwt.issue(&user(), "admin", None, None).unwrap();

        assert_ne!(
            first.jti, second.jti,
            "revoking one must not revoke the other"
        );
    }

    #[tokio::test]
    async fn an_expired_token_is_refused() {
        let (_db, _secrets, jwt) = issuer().await;

        let (token, _) = jwt
            .issue(&user(), "admin", None, Some(Duration::seconds(-120)))
            .unwrap();

        assert!(jwt.verify(&token).is_err());
    }

    #[tokio::test]
    async fn a_token_within_the_leeway_is_still_accepted() {
        let (_db, _secrets, jwt) = issuer().await;

        let (token, _) = jwt
            .issue(&user(), "admin", None, Some(Duration::seconds(-30)))
            .unwrap();

        assert!(
            jwt.verify(&token).is_ok(),
            "60 seconds of clock skew is tolerated"
        );
    }

    #[tokio::test]
    async fn a_token_for_another_audience_or_issuer_is_refused() {
        let (db, secrets, jwt) = issuer().await;
        let (token, _) = jwt.issue(&user(), "admin", None, None).unwrap();

        let other_audience = JwtIssuer::load_or_create(
            &db,
            &secrets,
            &crate::config::AuthConfig {
                audience: "somebody-else".to_string(),
                ..auth()
            },
            "https://unused",
        )
        .await
        .unwrap();
        let other_issuer = JwtIssuer::load_or_create(
            &db,
            &secrets,
            &crate::config::AuthConfig {
                issuer: Some("https://impostor.example".to_string()),
                ..auth()
            },
            "https://unused",
        )
        .await
        .unwrap();

        assert!(other_audience.verify(&token).is_err());
        assert!(other_issuer.verify(&token).is_err());
    }

    #[tokio::test]
    async fn a_token_signed_by_another_server_is_refused() {
        let (_db, _secrets, jwt) = issuer().await;
        let stranger = Database::open_in_memory().await.unwrap();
        let other = JwtIssuer::load_or_create(
            &stranger,
            &SecretStore::ephemeral(),
            &auth(),
            "https://unused",
        )
        .await
        .unwrap();

        let (token, _) = other.issue(&user(), "admin", None, None).unwrap();

        assert_ne!(other.active_kid(), jwt.active_kid());
        assert!(jwt.verify(&token).is_err());
    }

    #[tokio::test]
    async fn an_hs256_or_unsigned_token_is_refused() {
        let (_db, _secrets, jwt) = issuer().await;
        let (token, claims) = jwt.issue(&user(), "admin", None, None).unwrap();
        let payload = token.split('.').nth(1).unwrap();

        // The two classic forgeries: swap the algorithm to `none`, or to an
        // HMAC keyed on the public key we publish.
        for header in [
            r#"{"alg":"none","typ":"JWT"}"#,
            r#"{"alg":"HS256","typ":"JWT"}"#,
        ] {
            let forged = format!("{}.{payload}.", B64.encode(header));

            assert!(jwt.verify(&forged).is_err(), "{header}");
        }

        let hs256 = jsonwebtoken::encode(
            &jsonwebtoken::Header::new(Algorithm::HS256),
            &claims,
            &EncodingKey::from_secret(b"guess"),
        )
        .unwrap();
        assert!(jwt.verify(&hs256).is_err());
    }

    #[tokio::test]
    async fn a_tampered_payload_is_refused() {
        let (_db, _secrets, jwt) = issuer().await;
        let (token, mut claims) = jwt.issue(&user(), "marti", None, None).unwrap();
        claims.scope = "admin".to_string();

        let mut parts = token.split('.');
        let forged = format!(
            "{}.{}.{}",
            parts.next().unwrap(),
            B64.encode(serde_json::to_vec(&claims).unwrap()),
            parts.nth(1).unwrap()
        );

        assert!(jwt.verify(&forged).is_err());
        assert!(jwt.verify("not-a-token").is_err());
        assert!(jwt.verify("").is_err());
    }

    #[tokio::test]
    async fn the_key_survives_a_restart() {
        let (db, secrets, jwt) = issuer().await;
        let (token, _) = jwt.issue(&user(), "admin", None, None).unwrap();

        let restarted = JwtIssuer::load_or_create(&db, &secrets, &auth(), "https://unused")
            .await
            .unwrap();

        assert_eq!(restarted.active_kid(), jwt.active_kid());
        assert!(restarted.verify(&token).is_ok());
    }

    #[tokio::test]
    async fn a_token_signed_before_a_rotation_still_verifies() {
        let (db, secrets, mut jwt) = issuer().await;
        let (before, _) = jwt.issue(&user(), "admin", None, None).unwrap();
        let old_kid = jwt.active_kid().to_string();

        jwt.rotate(&db, &secrets).await.unwrap();
        let (after, _) = jwt.issue(&user(), "admin", None, None).unwrap();

        assert_ne!(jwt.active_kid(), old_kid);
        assert!(
            jwt.verify(&before).is_ok(),
            "the retired key still verifies"
        );
        assert!(jwt.verify(&after).is_ok());

        // And a restart picks the rotation up rather than resurrecting the old
        // key as the active one.
        let restarted = JwtIssuer::load_or_create(&db, &secrets, &auth(), "https://unused")
            .await
            .unwrap();
        assert_eq!(restarted.active_kid(), jwt.active_kid());
        assert!(restarted.verify(&before).is_ok());
    }

    #[tokio::test]
    async fn the_published_key_material_is_public_only() {
        let (_db, _secrets, jwt) = issuer().await;

        let token_key = jwt.token_key_json();
        let jwks = jwt.jwks();

        assert_eq!(token_key["alg"], "SHA256withRSA");
        let pem = token_key["value"].as_str().unwrap();
        assert!(pem.starts_with("-----BEGIN PUBLIC KEY-----"), "{pem}");
        assert!(!pem.contains("PRIVATE"), "{pem}");

        let key = &jwks["keys"][0];
        assert_eq!(key["kty"], "RSA");
        assert_eq!(key["alg"], "RS256");
        assert_eq!(key["use"], "sig");
        assert_eq!(key["kid"], jwt.active_kid());
        assert!(key["n"].as_str().unwrap().len() > 300, "a 2048-bit modulus");
        assert!(
            jwks["keys"][1].is_null(),
            "only one key before any rotation"
        );
        assert!(!jwks.to_string().contains('d'.to_string().as_str()) || key["d"].is_null());
    }

    #[tokio::test]
    async fn the_stored_key_is_sealed() {
        let (db, secrets, jwt) = issuer().await;

        let row = db
            .oauth_keys()
            .get(jwt.active_kid())
            .await
            .unwrap()
            .unwrap();

        assert_eq!(row.alg, KeyAlgorithm::Rs256);
        assert_eq!(row.purpose, KeyPurpose::AccessToken);
        assert!(!row.private_sealed.contains("PRIVATE"));
        assert!(row.public_jwk.unwrap().contains("\"kty\":\"RSA\""));
        assert!(!format!("{jwt:?}").contains(&row.private_sealed));

        // A different encryption key cannot open it.
        assert!(
            JwtIssuer::load_or_create(&db, &SecretStore::ephemeral(), &auth(), "https://unused")
                .await
                .is_err()
        );
        let _ = secrets;
    }

    #[tokio::test]
    async fn the_issuer_falls_back_to_the_server_url() {
        let db = Database::open_in_memory().await.unwrap();
        let jwt = JwtIssuer::load_or_create(
            &db,
            &SecretStore::ephemeral(),
            &crate::config::AuthConfig::default(),
            "https://tak.example.com:8446",
        )
        .await
        .unwrap();

        let (_, claims) = jwt.issue(&user(), "admin", None, None).unwrap();

        assert_eq!(jwt.issuer(), "https://tak.example.com:8446");
        assert_eq!(claims.iss, "https://tak.example.com:8446");
        assert_eq!(jwt.audience(), "rustak");
    }
}
