//! The routed pages.

mod activity;
mod auth_callback;
mod cot_browser;
mod cot_drawer;
mod dashboard;
#[cfg(debug_assertions)]
mod demo;
mod eud_rows;
mod euds;
mod group_members;
mod groups;
mod landing;
mod load;
mod login;
mod map;
mod me;
mod mission_changes;
mod mission_detail;
mod mission_overview;
mod mission_tabs;
mod missions;
mod not_found;
mod package_row;
mod packages;
mod panels;
mod profile_delivery;
mod profile_editor;
mod profile_files;
mod profile_prefs;
mod profiles;
mod protected;
mod service_config;
mod service_detail;
mod service_metrics;
mod services;
mod settings_files;
mod settings_security;
mod settings_storage;
mod settings_tls;
mod setup;
mod user_create;
mod user_detail;
mod users;

pub use activity::Activity;
pub use auth_callback::AuthCallback;
pub use cot_browser::Situation;
pub use dashboard::Dashboard;
#[cfg(debug_assertions)]
pub use demo::DemoControls;
pub use euds::Euds;
pub use groups::Groups;
pub use landing::Landing;
pub use login::Login;
pub use map::LiveMap;
pub use me::Me;
pub use mission_detail::MissionDetailPage;
pub use missions::Missions;
pub use not_found::NotFound;
pub use packages::Packages;
pub use profile_editor::ProfileEditor;
pub use profiles::Profiles;
pub use protected::Protected;
pub use services::Services;
pub use settings_security::Security;
pub use settings_storage::Storage;
pub use setup::Setup;
pub use user_detail::UserDetail;
pub use users::Users;
