/**
 * The rustak the stack runs: its configuration, and where the runner finds it.
 *
 * Unlike `interop/node-tak` and `interop/eud`, this suite does not start a
 * process — rustak is a container on CloudTAK's network, because CloudTAK has
 * to reach it by a name that resolves inside that network. What is shared is
 * everything above the process boundary: `interop/shared/src/config.ts` renders
 * this file's tables, and `interop/shared/src/bootstrap.ts` performs the
 * cold-start walk against the published port afterwards.
 *
 * Two things are deliberately different from the other suites:
 *
 * 1. **`[web.public.tls] mode = "files"`**, from `src/pki.ts` — the deployment
 *    an operator running CloudTAK against an internal CA is pushed into.
 * 2. **`[server] base_url` names `localhost`**, not the container's own name.
 *    WebAuthn binds a passkey to a domain, and the bootstrap's passkey is
 *    registered from the *host* against the published port; `localhost` is also
 *    the one relying party rustak accepts on any port, so the published port
 *    need not match the bound one. CloudTAK still reaches the same listener at
 *    `https://rustak:8446`, which is what its three URLs record.
 */

import fs from "node:fs";
import path from "node:path";

import { mergeConfig, renderConfig, type ConfigTables } from "../../shared/src/config.js";
import type { ServerInfo } from "../../shared/src/launch.js";

import { PKI } from "./pki.js";
import { CONTAINER_TLS, DATA_DIR, HOST_URLS, NAMES, PORTS } from "./settings.js";

/** The ports rustak binds *inside* the container, which never move. */
const BOUND = { web: 8446, marti: 8443, stream: 8089 } as const;

/** The configuration the container is started with. */
export function configuration(overrides: ConfigTables = {}): ConfigTables {
  return mergeConfig(
    {
      server: {
        name: "rustak-interop-cloudtak",
        // `localhost` first: it is the canonical name, the relying party the
        // bootstrap's passkey is registered against, and the subject of the
        // internal server certificate. `rustak` is how CloudTAK reaches the
        // same listener from inside the compose network.
        domains: ["localhost", "rustak"],
        base_url: `https://localhost:${BOUND.web}`,
        data_dir: "/data",
      },
      storage: { reader_connections: 1 },
      "web.public": { listen: [`:${BOUND.web}`] },
      "web.public.tls": {
        mode: "files",
        cert_file: CONTAINER_TLS.cert,
        key_file: CONTAINER_TLS.key,
      },
      "web.marti": { enabled: true, listen: `:${BOUND.marti}`, client_cert: "required" },
      marti: {
        // CloudTAK's setup wizard refuses to save a connection until
        // `/files/api/config` answers with an integer here — the single
        // highest-priority endpoint in the whole surface (compat/cloudtak.md §2).
        upload_size_limit_mb: 400,
      },
      "stream.tls": { enabled: true, listen: `:${BOUND.stream}` },
      auth: {
        // No identity provider in the stack, so both filters would otherwise
        // deny everybody.
        user_acl: "true",
        admin_acl: "true",
        // The credential CloudTAK authenticates with: the password grant on
        // `/oauth/token` and Basic on `signClient/v2`, and nothing else.
        client_passwords_enabled: true,
      },
    },
    overrides,
  );
}

/** Writes the configuration into the directory the container mounts at `/data`. */
export function writeConfiguration(overrides: ConfigTables = {}): string {
  fs.mkdirSync(DATA_DIR, { recursive: true });

  const file = path.join(DATA_DIR, "config.toml");

  fs.writeFileSync(
    file,
    `# Generated by interop/cloudtak/src/rustak.ts. Do not edit; it is thrown away.\n${renderConfig(configuration(overrides))}`,
    "utf8",
  );

  return file;
}

/**
 * Where the runner finds the server, in the shape `interop/shared` expects.
 *
 * `dataDir` is the host side of the bind mount, which is what lets the shared
 * bootstrap read the one-time setup token the server writes at first start —
 * the only route to a first administrator.
 */
export function serverInfo(): ServerInfo {
  return {
    directory: DATA_DIR,
    dataDir: DATA_DIR,
    caFile: PKI.caCert,
    webtak: HOST_URLS.webtak,
    api: HOST_URLS.marti,
    stream: HOST_URLS.stream,
    host: "localhost",
    ports: { web: PORTS.webtak, marti: PORTS.marti, stream: PORTS.stream },
  };
}

/** What the bootstrap records through the setup wizard. */
export const WIZARD = {
  adminUsername: NAMES.admin,
  displayName: "CloudTAK interop suite",
  serverName: "rustak-interop-cloudtak",
  domains: ["localhost", "rustak"],
  baseUrl: `https://localhost:${BOUND.web}`,
} as const;
