//! Generating and reloading the private keys rustak owns.
//!
//! These are the keys behind the certificate authority and the server
//! certificates it issues. Client keys are never generated here: a device makes
//! its own key and sends us a signing request, which is the whole point of
//! asking for one.
//!
//! # Why RSA comes from the `rsa` crate rather than from rcgen
//!
//! rcgen signs with `aws-lc-rs`, and `aws-lc-rs` can generate RSA keys — but it
//! does so in C, which is exactly the part of the build that makes
//! cross-compiling to the musl and aarch64 targets rustak ships awkward. The
//! pure-Rust `rsa` crate generates the key, we hand rcgen the PKCS#8 encoding
//! of it, and signing carries on through `aws-lc-rs` as before. Elliptic-curve
//! keys are generated by rcgen directly, because that path has no such cost.
//!
//! RSA key generation is measured in hundreds of milliseconds, so every caller
//! that has a runtime to block runs [`generate_key`] on a blocking thread.

use rustak_core::prelude::*;
use rustls_pki_types::PrivatePkcs8KeyDer;

pub use crate::config::KeyType;

/// Advice for a key operation that failed for reasons we cannot explain.
const ADVICE_KEY: &[&str] = &[
    "This is unexpected; please report it with the surrounding log entries.",
    "If it recurs, set 'key_type' under [pki] to 'ecdsa-p256' and try again.",
];

/// The signature algorithm certificates signed by a key of this type carry.
pub fn signature_algorithm(kind: KeyType) -> &'static rcgen::SignatureAlgorithm {
    match kind {
        KeyType::Rsa2048 | KeyType::Rsa3072 => &rcgen::PKCS_RSA_SHA256,
        KeyType::EcdsaP256 => &rcgen::PKCS_ECDSA_P256_SHA256,
    }
}

/// How many bits an RSA key of this type has, or `None` for a curve.
fn rsa_bits(kind: KeyType) -> Option<usize> {
    match kind {
        KeyType::Rsa2048 => Some(2048),
        KeyType::Rsa3072 => Some(3072),
        KeyType::EcdsaP256 => None,
    }
}

/// Generates a fresh private key.
///
/// Blocking and, for RSA, slow: run it through
/// [`tokio::task::spawn_blocking`] from anything with a runtime to hold up.
///
/// # Errors
///
/// A [`human_errors::Kind::System`] error when the key cannot be generated or
/// cannot be re-parsed for signing.
pub fn generate_key(kind: KeyType) -> Result<rcgen::KeyPair, Error> {
    let Some(bits) = rsa_bits(kind) else {
        return rcgen::KeyPair::generate_for(signature_algorithm(kind)).or_system_err(ADVICE_KEY);
    };

    let key =
        rsa::RsaPrivateKey::new(&mut rsa::rand_core::OsRng, bits).or_system_err(ADVICE_KEY)?;

    let pkcs8 = rsa::pkcs8::EncodePrivateKey::to_pkcs8_der(&key).or_system_err(ADVICE_KEY)?;

    key_pair_from_pkcs8(pkcs8.as_bytes(), kind)
}

/// Rebuilds a signing key from the PKCS#8 encoding we stored.
///
/// The key type is passed rather than inferred: several signature algorithms
/// fit the same RSA key, and a certificate whose signature algorithm changed
/// between runs because the guess changed would be a hard failure to explain.
///
/// # Errors
///
/// A [`human_errors::Kind::System`] error when the bytes are not a private key
/// of that type.
pub fn key_pair_from_pkcs8(der: &[u8], kind: KeyType) -> Result<rcgen::KeyPair, Error> {
    rcgen::KeyPair::from_pkcs8_der_and_sign_algo(
        &PrivatePkcs8KeyDer::from(der),
        signature_algorithm(kind),
    )
    .or_system_err(&[
        "The stored private key could not be read; it may have been written by a different version of rustak.",
        "If the problem persists, the certificate and its key must be recreated.",
    ])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn an_ecdsa_key_round_trips_through_its_pkcs8_encoding() {
        let generated = generate_key(KeyType::EcdsaP256).unwrap();
        let reloaded = key_pair_from_pkcs8(&generated.serialize_der(), KeyType::EcdsaP256).unwrap();

        assert_eq!(generated.public_key_raw(), reloaded.public_key_raw());
        assert_eq!(reloaded.algorithm(), &rcgen::PKCS_ECDSA_P256_SHA256);
    }

    #[test]
    fn an_rsa_key_round_trips_through_its_pkcs8_encoding() {
        let generated = generate_key(KeyType::Rsa2048).unwrap();
        let reloaded = key_pair_from_pkcs8(&generated.serialize_der(), KeyType::Rsa2048).unwrap();

        assert_eq!(generated.public_key_raw(), reloaded.public_key_raw());
        assert_eq!(reloaded.algorithm(), &rcgen::PKCS_RSA_SHA256);
    }

    #[test]
    fn every_key_type_signs_with_the_algorithm_its_certificates_declare() {
        for kind in [KeyType::Rsa2048, KeyType::Rsa3072, KeyType::EcdsaP256] {
            assert_eq!(
                rsa_bits(kind).is_some(),
                signature_algorithm(kind) == &rcgen::PKCS_RSA_SHA256,
                "{kind:?}"
            );
        }
    }

    #[test]
    fn two_generated_keys_are_different_keys() {
        let first = generate_key(KeyType::EcdsaP256).unwrap();
        let second = generate_key(KeyType::EcdsaP256).unwrap();

        assert_ne!(first.public_key_raw(), second.public_key_raw());
    }

    #[test]
    fn rubbish_is_not_a_private_key() {
        assert!(key_pair_from_pkcs8(b"not a key", KeyType::EcdsaP256).is_err());
        assert!(key_pair_from_pkcs8(&[], KeyType::Rsa2048).is_err());
    }

    #[test]
    fn a_key_never_renders_its_secret_half() {
        // rcgen redacts it, but this is the property we depend on when a
        // `KeyPair` ends up inside something a tracing macro touches.
        let key = generate_key(KeyType::EcdsaP256).unwrap();

        assert!(!format!("{key:?}").contains(&hex::encode(key.serialize_der())));
    }
}
