//! The expensive key material the tests share: made once per build, read by
//! every test process after that.
//!
//! A [`TestServer`](super::TestServer) is cheap except for one thing: the RSA
//! key its [`JwtIssuer`](crate::auth::JwtIssuer) signs with. The identity
//! provider, the orchestrator and the software authenticator each want RSA keys
//! of their own too. Generating one is a prime search — 0.2–0.3 s on a laptop
//! core, 1–2 s under `-Cinstrument-coverage` — and under nextest every test is
//! a process of its own, so a key held in a process-wide `LazyLock` alone was
//! generated once per *test*: seconds of every server test in the coverage run.
//!
//! So every RSA key here is [`rsa`]`(name)`: the first process to ask for a
//! name generates it and leaves it in a file; every later process, in this run
//! or the next, reads and parses the file instead. Inside one process the
//! `LazyLock`s in front of it still make that happen at most once per name.
//! How many processes starting at once agree on one maker, and why a reader
//! never sees half a file, is [`key_file`](super::key_file)'s business.
//!
//! # Where the files live
//!
//! Beside the test binaries: `<target>/<profile>/rustak-test-keys/<name>.pk8`.
//! Cargo's `CARGO_TARGET_TMPDIR` would be the obvious place, but Cargo sets it
//! only when compiling integration tests and benchmarks — not the library,
//! whose unit tests and `testing` feature are where these keys are made. A
//! process that is not a test binary in `<target>/<profile>/deps/` (a doctest,
//! say) keeps its keys in memory and writes nothing.
//!
//! # Threat model
//!
//! **These keys protect nothing.** They sign tokens for servers that exist for
//! one test, trusted by nothing outside the test. The files live and die with
//! `target/` (`cargo clean` removes them), are never checked in — no private
//! key is in this repository — and are written owner-only on Unix anyway.
//! Nothing a deployment can reach reads from here: this module is compiled
//! only under `cfg(test)` or the `testing` feature, and the production issuer
//! only ever generates its keys or loads them from its own database. Anybody
//! who can write to `target/` can already replace the test binaries
//! themselves, so a planted key file gains them nothing.
//!
//! What is *not* shared is anything a test can observe: databases, data
//! directories, secret stores and content stores all stay per test, and the
//! sealed copy of the signing key that each server stores is sealed under that
//! server's own secret store. Two tests merely sign with the same key, exactly
//! as two restarts of one deployment would. Tests that are *about* generating
//! or rotating a key still generate one.

use std::sync::LazyLock;

use rsa::pkcs8::{DecodePrivateKey as _, EncodePrivateKey as _};
use rsa::traits::PublicKeyParts as _;

use super::key_file;
use crate::config::Config;

/// The size the production issuer generates, so that a test signs the same
/// shape of token a deployment does.
const KEY_BITS: usize = 2048;

/// The token signing key every test server adopts, as PKCS#8 DER.
///
/// # Panics
///
/// If a key cannot be generated or encoded, which no test can carry on past.
pub static JWT_SIGNING_KEY: LazyLock<Vec<u8>> = LazyLock::new(|| {
    rsa("jwt-signing")
        .to_pkcs8_der()
        .expect("the test signing key encodes")
        .as_bytes()
        .to_vec()
});

/// The RSA-2048 key called `name`, generated by the first test process that
/// asks for it and read back by every one after.
///
/// Distinct names are distinct keys: a forgery needs a key that is not the
/// one advertised, and the tests that check a forgery is refused would pass
/// for the wrong reason if two names ever shared one. Call it from behind a
/// `LazyLock`, so a process parses each key once.
///
/// # Panics
///
/// If a key cannot be generated or encoded. A key file that cannot be read,
/// parsed or written never panics: it costs a generation, nothing more.
pub fn rsa(name: &str) -> rsa::RsaPrivateKey {
    match key_file::directory() {
        Some(directory) => key_file::load_or_make(&directory, name, parse, generate),
        None => parse(&generate()).expect("a key that was just generated parses"),
    }
}

/// Stores the shared signing key in the database a
/// [`build_context`](crate::build_context) over `config` will open.
///
/// `build_context` is start-up's own path, and start-up generates a key when
/// the database holds none. A harness that calls this first gets the second
/// start instead — the key is loaded, not generated — while everything after
/// it is unchanged. Only for a harness whose tests are not about the key; one
/// that is should let start-up generate.
///
/// # Panics
///
/// If the database or the secret store under `config` cannot be opened, or
/// the key cannot be stored, none of which a test can carry on past.
pub async fn adopt_signing_key(config: &Config) {
    let database_path = config.database_path();

    let db = crate::db::Database::open(
        &database_path,
        config.storage.reader_connections,
        crate::db::connection::DEFAULT_BUSY_TIMEOUT,
    )
    .await
    .expect("the database the server under test will open");

    let secrets = crate::crypto::SecretStore::load(
        config.auth.secret_key.as_deref(),
        &config.auth.previous_secret_keys,
        &database_path,
    )
    .expect("the secret store the server under test will open");

    crate::auth::JwtIssuer::load_or_adopt(
        &db,
        &secrets,
        &config.auth,
        "https://unused.invalid",
        &JWT_SIGNING_KEY,
    )
    .await
    .expect("the shared signing key is stored");

    db.close()
        .await
        .expect("the database closes before the server opens it");
}

/// A fresh RSA key, as PKCS#8 DER.
fn generate() -> Vec<u8> {
    rsa::RsaPrivateKey::new(&mut rsa::rand_core::OsRng, KEY_BITS)
        .expect("generate an RSA key for the tests")
        .to_pkcs8_der()
        .expect("the generated key encodes")
        .as_bytes()
        .to_vec()
}

/// An RSA key of the size the tests expect, or nothing.
fn parse(bytes: &[u8]) -> Option<rsa::RsaPrivateKey> {
    rsa::RsaPrivateKey::from_pkcs8_der(bytes)
        .ok()
        .filter(|key| key.size() * 8 == KEY_BITS)
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use super::*;

    #[test]
    fn the_shared_key_is_one_key_and_a_usable_one() {
        // Two reads are the same bytes — that is the whole point — and they
        // parse as the RSA key the issuer expects rather than as some other
        // encoding that happens to be the right length.
        assert_eq!(*JWT_SIGNING_KEY, *JWT_SIGNING_KEY);

        let key = rsa::RsaPrivateKey::from_pkcs8_der(&JWT_SIGNING_KEY).expect("the key parses");

        assert_eq!(key.size() * 8, KEY_BITS);
    }

    #[test]
    fn the_key_a_process_uses_is_the_one_it_leaves_for_the_next() {
        // Whether this process made the key or read it, the file now holds
        // it, and the next process to start will sign with the same one.
        let shared = rsa::RsaPrivateKey::from_pkcs8_der(&JWT_SIGNING_KEY).unwrap();
        let directory = key_file::directory().expect("a test binary runs from deps/");
        let bytes = std::fs::read(directory.join("jwt-signing.pk8")).expect("the key was left");

        assert_eq!(parse(&bytes).expect("the file holds a key"), shared);
    }

    #[test]
    fn a_test_binary_keeps_its_keys_beside_the_binaries() {
        // This test runs from `<target>/<profile>/deps/`, under both runners,
        // so the keys go in the profile directory — inside `target/`, where
        // `cargo clean` finds them.
        let directory = key_file::directory().expect("a test binary runs from deps/");
        let executable = std::env::current_exe().unwrap();

        assert_eq!(directory.file_name().unwrap(), key_file::DIRECTORY);
        assert_eq!(
            directory.parent(),
            executable.parent().and_then(Path::parent)
        );
    }

    #[test]
    fn a_key_of_the_wrong_size_is_not_a_key() {
        // A file from a build that used a different size must be replaced,
        // not signed with. 512 bits keeps the generation cheap.
        let small = rsa::RsaPrivateKey::new(&mut rsa::rand_core::OsRng, 512)
            .unwrap()
            .to_pkcs8_der()
            .unwrap();

        assert!(parse(small.as_bytes()).is_none());
        assert!(parse(b"not a key").is_none());
    }
}
