//! The expensive key material every test in a process shares.
//!
//! A [`TestServer`](super::TestServer) is cheap except for one thing: the RSA
//! key its [`JwtIssuer`](crate::auth::JwtIssuer) signs with. Generating one is
//! bignum arithmetic measured in hundreds of milliseconds unoptimised, and the
//! suite builds well over two hundred servers — so on a two-core CI runner
//! under `-Cinstrument-coverage` that one line was most of the wall clock, and
//! individual endpoint tests were being reported as "running for over 60
//! seconds".
//!
//! So the key is generated once, lazily, per test process and handed to every
//! server built in it. What is *not* shared is anything a test can observe:
//! databases, data directories, secret stores and content stores all stay per
//! test, and the sealed copy of this key that each server stores is sealed
//! under that server's own ephemeral secret store. Two tests still cannot see
//! one another's rows — they merely sign with the same key, exactly as two
//! restarts of one deployment would.
//!
//! The key is still RSA-2048, still generated by the same `rsa` crate the
//! production path uses, and still travels through
//! [`JwtIssuer::load_or_adopt`](crate::auth::JwtIssuer::load_or_adopt) into the
//! same sealing and storage. Nothing about the token format under test changes.

use std::sync::LazyLock;

use rsa::pkcs8::EncodePrivateKey as _;

/// The size the production issuer generates, so that a test signs the same
/// shape of token a deployment does.
const KEY_BITS: usize = 2048;

/// One RSA-2048 private key in PKCS#8 DER, minted the first time a test in this
/// process asks for it.
///
/// # Panics
///
/// If a key cannot be generated or encoded, which no test can carry on past.
pub static JWT_SIGNING_KEY: LazyLock<Vec<u8>> = LazyLock::new(|| {
    rsa::RsaPrivateKey::new(&mut rsa::rand_core::OsRng, KEY_BITS)
        .expect("a signing key for the tests in this process")
        .to_pkcs8_der()
        .expect("the test signing key encodes")
        .as_bytes()
        .to_vec()
});

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_shared_key_is_one_key_and_a_usable_one() {
        // Two reads are the same bytes — that is the whole point — and they
        // parse as the RSA key the issuer expects rather than as some other
        // encoding that happens to be the right length.
        assert_eq!(*JWT_SIGNING_KEY, *JWT_SIGNING_KEY);

        let key =
            <rsa::RsaPrivateKey as rsa::pkcs8::DecodePrivateKey>::from_pkcs8_der(&JWT_SIGNING_KEY)
                .expect("the shared key parses");

        assert_eq!(rsa::traits::PublicKeyParts::size(&key) * 8, KEY_BITS);
    }
}
