-- Room in `certificates.issued_via` for a certificate bought with an
-- orchestrator's workload identity.
--
-- M9-06 adds a third way for a sidecar to get a certificate: it presents the
-- JWT its orchestrator already gave it (a Nomad `identity` block, a Kubernetes
-- projected service-account token) instead of a one-time enrolment token, and
-- `POST /Marti/api/tls/signClient/v2` issues against that. `issued_via` is the
-- column that records which endpoint and which credential a certificate came
-- out of, and this is the value that says so: `workload_identity`.
--
-- It is not decoration. `[auth.workload] revoke_previous` — on by default —
-- takes back an account's *earlier* workload certificates whenever a new one is
-- issued, so that a task rescheduled onto another node does not leave a live
-- certificate on the old node's volume. The query that finds them matches this
-- column exactly, which is why the issuer's name is recorded in the audit trail
-- rather than folded into the value: one account, one stable token to match.
--
-- `source` stays `enrollment`: the key was generated by the client and only the
-- signing request crossed the wire, exactly as for an enrolment token.
--
-- # Why the whole table is rebuilt for one value
--
-- The allowed set is a CHECK constraint and SQLite cannot alter one in place
-- (`conventions.md`, "Storage"), so this repeats 0018's rebuild: same columns,
-- same order, same indexes, one more value. The two foreign keys that point at
-- this table are handled the same way — the self-reference is declared against
-- the new table's own name so the drop below is not a drop of its parent, and
-- `devices.last_certificate_id` is copied out and put back, because its table
-- is not being rebuilt and `ON DELETE SET NULL` would otherwise empty it.

-- Which certificate each device last presented, saved from the drop below.
CREATE TABLE certificates_device_link AS
  SELECT id, last_certificate_id FROM devices WHERE last_certificate_id IS NOT NULL;

-- Identical to the table 0018 left behind, with 'workload_identity' added to
-- the `issued_via` set and the self-reference pointed at this table's own name.
CREATE TABLE certificates_migrated (
  id            INTEGER PRIMARY KEY,
  kind          TEXT NOT NULL CHECK (kind IN ('ca','server','client','service')),
  source        TEXT NOT NULL DEFAULT 'internal'
                  CHECK (source IN ('enrollment','admin_package','internal','acme','imported')),
  issued_via    TEXT CHECK (issued_via IS NULL OR issued_via IN
                  ('enroll_v2_json','enroll_v2_xml','enroll_v1_p12','admin_package',
                   'acme_internal','cloudtak_onboarding','workload_identity')),
  serial_hex    TEXT NOT NULL,
  fingerprint   TEXT NOT NULL,
  subject_cn    TEXT NOT NULL,
  san           TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(san)),
  user_id       INTEGER REFERENCES users(id)   ON DELETE SET NULL,
  device_id     INTEGER REFERENCES devices(id) ON DELETE SET NULL,
  client_uid    TEXT,
  credential_id INTEGER REFERENCES credentials(id) ON DELETE SET NULL,
  issuer_id     INTEGER REFERENCES certificates_migrated(id) ON DELETE SET NULL,
  der           BLOB NOT NULL,
  key_sealed    TEXT CHECK (key_sealed IS NULL OR json_valid(key_sealed)),
  not_before    TEXT NOT NULL,
  not_after     TEXT NOT NULL,
  last_seen_at  TEXT,
  revoked_at    TEXT,
  revocation_reason TEXT,
  revoked_by    TEXT,
  created_at    TEXT NOT NULL
) STRICT;

INSERT INTO certificates_migrated (
  id, kind, source, issued_via, serial_hex, fingerprint, subject_cn, san,
  user_id, device_id, client_uid, credential_id, issuer_id, der, key_sealed,
  not_before, not_after, last_seen_at, revoked_at, revocation_reason,
  revoked_by, created_at
)
SELECT
  id, kind, source, issued_via, serial_hex, fingerprint, subject_cn, san,
  user_id, device_id, client_uid, credential_id, issuer_id, der, key_sealed,
  not_before, not_after, last_seen_at, revoked_at, revocation_reason,
  revoked_by, created_at
FROM certificates;

DROP TABLE certificates;

ALTER TABLE certificates_migrated RENAME TO certificates;

UPDATE devices
   SET last_certificate_id = (
         SELECT last_certificate_id
           FROM certificates_device_link
          WHERE certificates_device_link.id = devices.id
       )
 WHERE id IN (SELECT id FROM certificates_device_link);

DROP TABLE certificates_device_link;

-- The indexes went with the old table; they are the same seven 0002 created.
CREATE UNIQUE INDEX idx_certificates_fingerprint ON certificates (fingerprint);
CREATE UNIQUE INDEX idx_certificates_issuer_serial ON certificates (issuer_id, serial_hex);
CREATE INDEX idx_certificates_user ON certificates (user_id);
CREATE INDEX idx_certificates_device ON certificates (device_id);
CREATE INDEX idx_certificates_credential ON certificates (credential_id);
CREATE INDEX idx_certificates_expiry ON certificates (kind, not_after) WHERE revoked_at IS NULL;
CREATE INDEX idx_certificates_revoked ON certificates (revoked_at) WHERE revoked_at IS NOT NULL;
